### ISSUE TITLE
Adding person results in duplicate person in the list view

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#325]
Steps:
1. Add a new person using the 'New' button

Bug: An existing person in the list is duplicated instead of new person getting added to the list

**Comment by damithc** [comment]
@yl-coder see if this is a UI bug or a model manager bug

**Comment by yl-coder** [comment]
I can't seems to reproduce this using the steps above.

**Comment by HansNewbie** [comment]
Might have been fixed in b89114429c45e0e59149c02be200220ab23955ce.

**Comment by damithc** [comment]
No, still happens. Try throwing in `Ctrl+Z` too.
e.g.
1. edit person
2. Ctrl+Z while the edit is pending
3. Add a new person

**Comment by m133225** [comment]
@damithc Does this reliably happen on your machine?

**Comment by yl-coder** [comment]
Can't reproduce using the mentioned steps also. One way to verify if it is a UI bug is to refresh the entire list by adding or delete a person(if the list data is corrected after the refresh, means it is a UI bug), or by opening the edit dialog to see if the information tally.

**Comment by YijinL** [comment]
Can't repro too

**Comment by HansNewbie** [comment]
Can't reproduce using 'New' or with undo.

**Comment by damithc** [comment]
Add more debug logs and I'll run in debug mode to collect more data.

**Comment by yl-coder** [comment]
@damithc Added more debug logs. You can pull the latest master.

**Comment by damithc** [comment]
Looks like I was using an older data file. Closing.
